import { StyleSheet } from "react-native";

const styles = StyleSheet.create({

    scrollView: {
      height: "100%",
      width: "100%",
      backgroundColor: "#ffffff",
      borderBottomWidth: 1,
      borderBottomColor: "#EFEFF1FE",
    },
      
    view__1: {
      height: 182,
      alignItems: "center",
      justifyContent: "center"
    },
    view__2: {
      width: "100%",
      alignItems: "center",
      justifyContent: "center",
      overflow: "hidden",
    },

    view_input_c_1: {
      height: 44,
      width: "92%",
      maxWidth: "92%",
      backgroundColor: "#F5F5F5",
      borderRadius: 40,
      display: "flex",
      flexDirection: "row",
      alignItems: "center",
      overflow: "hidden",
    },

    search_icon: {
      fontSize: 17,
      color: "#8F8D8DFE",
      width: 36,
      textAlign: "right",
      height: 44,
      paddingTop: 13,
    },
    mic_icon: {
      fontSize: 18,
      color: "#8F8D8DFE",
      height: 44,
      width: 36,
      paddingTop: 13,
    },
    search_text: {
      fontSize: 14,
      color: "#8F8D8DFE",
      marginLeft: 16,
      fontFamily: "Helvetica",
      flexGrow: 1,
    },

    view_3: {
      width: "100%",
      alignItems: "center",
      justifyContent: "center",
      flexDirection: "row",
      overflow: "hidden",
      marginTop: 32,
    },
    view_4: {
      width: "100%",
      alignItems: "center",
      justifyContent: "center",
      flexDirection: "row",
      overflow: "hidden",
      marginTop: 16,
    },
    view_3_imgc1: {
      marginTop: 4,
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: "#f5f5f5",
      height: 50,
      width: 50,
      borderRadius: 22,
      overflow: "hidden",
    },
    view_3_item_c: {
      width: "21%",
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: "#FFFFFF00",
    },
    view_item_img: {
      resizeMode: 'contain',
      width: 22,
      height: 22,
    },
    view_3_item_txt: {
      color: "#8F8D8DFE",
      fontSize: 12,
      marginTop: 4,
      fontFamily: "Helvetica",
    },

    view_5:{
      width: "100%",
      alignItems: "center",
      justifyContent: "center",
      flexDirection: "row",
      overflow: "hidden",
      marginTop: 32,
      marginBottom: 16,
    },
    view_5_ic_1:{
      flexGrow: 1,
      borderRadius: 100,
      overflow: "hidden",
      marginLeft: 20,
      marginRight: 20,
    },
    view_5_ic_2: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      borderRadius: 100,
      overflow: "hidden",
      paddingLeft: 16,
      paddingRight: 16,
      paddingTop: 4,
      paddingBottom: 4,
      borderColor: "#EFEFF1FE",
      borderWidth: 1.4,
    },
    view_5_txt: {
      color: "#8F8D8DFE",
      fontSize: 12.6,
      marginTop: 2,
      marginBottom: 2,
      fontFamily: "Helvetica",
      flexGrow: 1,
    },
    view_5_icon: {
      fontSize: 18,
      color: "#8F8D8DFE",
    },

    view_5_A_1: {
      width: "100%",
      marginBottom: 10,
      borderRadius: 12,
      overflow: "hidden",
    },
    view_5_A__1AA: {
      alignItems: "center",
      justifyContent: "center",
      flexDirection: "row",
      borderRadius: 12,
      overflow: "hidden",
      marginLeft: 20,
      marginRight: 20,
    },
    view_5_A__1AA__2: {
      alignItems: "center",
      justifyContent: "center",
      flexDirection: "row",
      borderRadius: 12,
      overflow: "hidden",
      marginLeft: 20,
      marginRight: 20,
      marginTop: 28,
      marginBottom: -10,
    },
    view_5_AA: {
      alignItems: "center",
      justifyContent: "center",
      flexDirection: "row",

      borderWidth: 1.4,
      borderColor: "#EFEFF1FE",
      borderRadius: 14,
      padding: 6,
    },
    view_5_A_2: {
      marginRight: 6,
    },
    view_5_A_3: {
      flex: 1,
      
    },
    view_5_A_4: {
      height: 50,
      marginRight: 10,
    },
    view_5_A_2_A: {
      resizeMode: "cover",
      height: 72,
      width: 72,
      borderRadius: 12,
      overflow: "hidden",
    },
    view_5_A_3_A: {
      fontFamily: "Helvetica",
      fontSize: 12,
      color: "#A2A1A1FE",
    },
    view_5_A_3_B: {
      fontFamily: "Helvetica",
      fontSize: 12,
      color: "#636B6FFE",
      paddingRight: 12,
    },
    view_5_A_3_A_2B: {
      fontSize: 12,
      fontFamily: "Helvetica",
      color: "#636B6FFE",
    },
    view_5_A_4_A: {
      fontSize: 13,
      color: "#A2A1A1FE",
      display: "flex",
      alignItems: "center",
      justifyContent: "flex-end",
    },
    icon_v5A3IN_1: {
      paddingRight: 6,
      alignItems: "center",
      justifyContent: "center",
    },
    view_heTxt_2BB: {
      color: "#A2A1A1FE",
      fontSize: 11,
    },
    view_heTxt_2CC: {
      color: "#A2A1A1FE",
      fontSize: 10,
    },
    loaderContainerAA: {
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      marginTop: 16,
    },
    browserMore__2: {
      width: "100%",
      textAlign: "center",
      marginTop: 0,
      marginBottom: 16,
      color: "#8F8D8DFE",
      fontSize: 14,
    },

    searchItemsBB_1: {
      width: "100%",
      display: "flex",
      flexDirection: "column",
      paddingBottom: 1000,
      marginTop: 10,
    },
    searchItemsBB_CON_1: {
      display: "flex",
      flexDirection: "row",
      marginTop: 10,
      marginLeft: 16,
      marginRight: 17,
      height: 32,
      alignItems: "center",
    },
    searchItemsBB_CON_2: {
      display: "flex",
      flexDirection: "row",
      marginTop: 10,
      marginLeft: 16,
      marginRight: 17,
      // height: 32,
      alignItems: "center",
    },
    searchItemsBB_1_A: {
      color: "#8c8e8ffe",
      marginLeft: 12,
      fontSize: 20,
    },
    searchItemsBB_1_B_CON: {
      flexGrow: 1,
    },
    searchItemsBB_1_B: {
      color: "#696A6CFE",
      marginLeft: 12,
      fontSize: 14,
    },
    searchItemsBB_1_B__2: {
      color: "#aaabacfe",
      marginLeft: 12,
      fontSize: 12,
    },
    searchItemsBB_1_C: {
      color: "#8c8e8ffe",
      marginRight: 12,
      fontSize: 20,
    },

    searchHeadingB_1: {
      color: "#9c9d9efe",
      fontSize: 11,
      marginLeft: 20,
      marginTop: 20,
    },

    modal4: {
      height: "auto",
      width: "90%",
      borderRadius: 4,
      elevation: 8,
    },

    modal8: {

      borderTopLeftRadius: 8,
      borderTopRightRadius: 8,
      height: "auto",
      width: "100%",
      elevation: 8,

      // borderRadius: 10,
      // height: "auto",
      // width: "96%",
      // elevation: 4,
      // bottom: 10,
      
    },
    pinAlertCont1_2_txt: {
      color: "#888787FE",
      fontSize: 15,
      fontFamily: "Helvetica",
      marginLeft: 10,
      paddingTop: 4,
    },
    pinAlertContAA: {
      display: "flex",
      flexDirection: "row",
      marginTop: 30,
    },
    pinAlertContBB: {
      display: "flex",
      flexDirection: "row",
      marginTop: 20,
    },
    pinAlertContCC: {
      display: "flex",
      flexDirection: "row",
      marginTop: 10,
      marginBottom: 30,
    },
    pinAlertCont1_3_ripple: {
      padding: 8,
      borderRadius: 100,
      overflow: "hidden",
    },
    pinAlertCont1_1_icon: {
      fontSize: 18,
      color: "#888787FE",
      marginLeft: 20,
      paddingTop: 4,
    },
    pinAlertCont1_3_icon: {
      fontSize: 20,
      color: "#888787FE",
    },
    pinAlertCont1_2: {
      flexGrow: 1,
    },
    pinAlertCont1_3: {
      marginRight: 20,
    },
    pinAlertCont1_B_1: {
      alignItems: "center",
      justifyContent: "center",
      marginRight: 14,
    },
    pinAlertCont1_B_2: {
      flexGrow: 1,
      marginRight: 20,
    },
    pinAlertCont1_C_1: {
      alignItems: "center",
      justifyContent: "center",
      marginRight: 14,
    },
    pinAlertCont1_C_2: {
      flexGrow: 1,
      marginRight: 20,
    },
    pinAlertContDD: {
      marginBottom: 30,
      display: "flex",
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "flex-end",
      marginRight: 20,
      marginTop: 10,
    },
    pinAlertCont1_B_1_TXT: {
      color: "#888787FE",
      fontSize: 14,
      fontFamily: "Helvetica",
      marginLeft: 20,
      width: 40,
    },
    pinAlertCont1_B_2_TXT: {
      color: "#888787FE",
      fontSize: 14,
      fontFamily: "Helvetica",
      marginLeft: 20,
      width: 40,
    },
    pinAlertCont1_D_1_TXT: {
      textTransform: "uppercase",
      fontSize: 14,
      marginLeft: 10,
      backgroundColor: "#F6F5F5FE",
      padding: 6,
      borderRadius: 2,
      paddingLeft: 14,
      paddingRight: 14,
      color: "#888787FE",
      // elevation: 2,
    },
    pinAlertCont1_D_2_TXT: {
      textTransform: "uppercase",
      fontSize: 14,
      marginLeft: 10,
      backgroundColor: "#888787FE",
      // backgroundColor: "#F6F5F5FE",
      padding: 6,
      borderRadius: 2,
      paddingLeft: 18,
      paddingRight: 18,
      color: "#F6F5F5FE",
      // color: "#888787FE",
      // elevation: 4,
    },
    pinAlertCont1_D_2_TXT_HIG: {
      textTransform: "uppercase",
      fontSize: 14,
      marginLeft: 10,
      backgroundColor: "#2196F2FF",
      padding: 6,
      borderRadius: 2,
      paddingLeft: 18,
      paddingRight: 18,
      color: "white",
      // elevation: 4,
    },

    optionAlertCont_MAIN: {
      paddingTop: 6,
    },
    optionAlertCont_opt_1: {
      paddingTop: 12,
      paddingBottom: 12,
      borderBottomWidth: 1.6,
      borderBottomColor: "#f1f1f1fe",
    },
    optionAlertCont_opt_1_B: {
      paddingTop: 12,
      paddingBottom: 16,
    },
    optionAlertCont_optText_1: {
      color: "#7a7878fe",
      fontSize: 15,
      textAlign: "center",
      display: "flex",
    },
    optionAlertCont_opt_icon_1: {
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
    },
    optionAlertCont_opt_icon_2: {
      color: "#929292fe",
      fontSize: 20,
    },

});

export default styles;