require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'TurboBrowserM' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-async-storage/async-storage'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'react-native-speech-to-text', :path => '../node_modules/react-native-google-speech-to-text'

  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'

  pod 'react-native-cookies', :path => '../node_modules/react-native-cookies'

  target 'TurboBrowserMTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'TurboBrowserM-tvOS' do
  # Pods for TurboBrowserM-tvOS

  target 'TurboBrowserM-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
